// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cau.Federico._5h.ECommerce.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20240601075447_primaversione")]
    partial class primaversione
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Cau.Tumidei._5h.ECommerce.Models.Jersey", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Prezzo")
                        .HasColumnType("REAL");

                    b.Property<string>("Squadra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taglia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipologia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Maglie");
                });

            modelBuilder.Entity("Cau.Tumidei._5h.ECommerce.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Datanascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUtente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Psw")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });
#pragma warning restore 612, 618
        }
    }
}
